//! rough-rs must match rough.js 4.6.4 (Excalidraw 0.18's pin) op for op.
//!
//! `tests/fixtures/rough/reference.json` is generated by `generate.ts` next
//! to it, using the option shapes Excalidraw passes. A failure here means
//! shapes would change when a scene moves between web Excalidraw and us.
use rough_rs::{Drawable, FillStyle, Generator, OpSetType, OpType, Options};
use serde_json::Value;

const REFERENCE: &str = include_str!("fixtures/rough/reference.json");

/// Op coordinates may differ by float reassociation only.
const TOLERANCE: f64 = 1e-9;

#[test]
fn matches_roughjs_for_fixed_seeds() {
    let doc: Value = serde_json::from_str(REFERENCE).unwrap();
    assert_eq!(doc["roughjs"], "4.6.4");
    let cases = doc["cases"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let got = generate(case);
        let want = case["sets"].as_array().unwrap();
        assert_eq!(got.sets.len(), want.len(), "{name}: set count");

        for (set, want) in got.sets.iter().zip(want) {
            assert_eq!(set_type(&set.set_type), want["type"], "{name}: set type");
            let want_ops = want["ops"].as_array().unwrap();
            assert_eq!(set.ops.len(), want_ops.len(), "{name}: op count");

            for (op, want) in set.ops.iter().zip(want_ops) {
                assert_eq!(op_type(&op.op), want["op"], "{name}: op kind");
                let want_data = want["data"].as_array().unwrap();
                assert_eq!(op.data.len(), want_data.len(), "{name}: op arity");
                for (got, want) in op.data.iter().zip(want_data) {
                    let want = want.as_f64().unwrap();
                    assert!((got - want).abs() < TOLERANCE, "{name}: {got} != {want}");
                }
            }
        }
    }
}

fn generate(case: &Value) -> Drawable {
    let o = &case["options"];
    let f = |k: &str| o.get(k).map(|v| v.as_f64().unwrap());
    let b = |k: &str| o.get(k).map(|v| v.as_bool().unwrap());
    let s = |k: &str| o.get(k).map(|v| v.as_str().unwrap().to_owned());
    let options = Some(Options {
        seed: o.get("seed").map(|v| v.as_u64().unwrap()),
        roughness: f("roughness"),
        stroke_width: f("strokeWidth"),
        fill_weight: f("fillWeight"),
        hachure_gap: f("hachureGap"),
        curve_fitting: f("curveFitting"),
        disable_multi_stroke: b("disableMultiStroke"),
        preserve_vertices: b("preserveVertices"),
        stroke: s("stroke"),
        fill: s("fill"),
        fill_style: s("fillStyle").map(|v| match v.as_str() {
            "hachure" => FillStyle::Hachure,
            "cross-hatch" => FillStyle::CrossHatch,
            "solid" => FillStyle::Solid,
            other => panic!("unexpected fill style {other}"),
        }),
        ..Options::default()
    });

    let args = &case["args"];
    let a = |i: usize| args[i].as_f64().unwrap();
    let points = || -> Vec<[f64; 2]> {
        let points = args[0].as_array().unwrap();
        points
            .iter()
            .map(|p| [p[0].as_f64().unwrap(), p[1].as_f64().unwrap()])
            .collect()
    };
    let generator = Generator::default();
    match case["call"].as_str().unwrap() {
        "rectangle" => generator.rectangle(a(0), a(1), a(2), a(3), options),
        "ellipse" => generator.ellipse(a(0), a(1), a(2), a(3), options),
        "circle" => generator.circle(a(0), a(1), a(2), options),
        "line" => generator.line(a(0), a(1), a(2), a(3), options),
        "polygon" => generator.polygon(&points(), options),
        "linearPath" => generator.linear_path(&points(), options),
        "curve" => generator.curve(&points(), options),
        "path" => generator.path(args[0].as_str().unwrap(), options),
        other => panic!("unexpected call {other}"),
    }
}

fn set_type(t: &OpSetType) -> &'static str {
    match t {
        OpSetType::Path => "path",
        OpSetType::FillPath => "fillPath",
        OpSetType::FillSketch => "fillSketch",
    }
}

fn op_type(t: &OpType) -> &'static str {
    match t {
        OpType::Move => "move",
        OpType::BCurveTo => "bcurveTo",
        OpType::LineTo => "lineTo",
    }
}
